### PR TITLE
Turkish spelling space fixing 

### PR DESCRIPTION
**Pull request by DuyguA**
### Changes proposed in this pull request:

Currently the spellings of the Turkish numbers are **wrong** . There should be spaces between each number word. 

I made a quick fix, however I'll make a refactoring when the time permits. Also code is not readable and more complicated than necessary.

### Status

- [x] READY

### How to verify this change

I modified the tests and add the corresponding spacing.

### Additional notes

You can check the corresponding TDK writing rule about the numbers in

https://www.tdk.gov.tr/icerik/yazim-kurallari/sayilarin-yazilisi/   

point **#2** . For instance

```
21 = yirmibir is wrong, the correct writing is yirmi=20 bir=1
```

Otherwise `1514` would be `binbesyuzondort` , definitely we don't have such a compounding rule in Turkish and we don't have such word compounds in our lexicon.

### CODE REVIEW

**Comment by toofun666** [comment]
There are 2 types of regulations regarding the reading of the numbers in Turkish:
1. with spaces between each word which is normal in writing and daily use
2. without spaces on accounting and legal documents such as invoices, cheques etc.
I don't recall but should be an overriden methods to produce both defaulted to the legal use

**Comment by toofun666** [comment]
> ### Changes proposed in this pull request:
> Currently the spellings of the Turkish numbers are **wrong** . There should be spaces between each number word.
> 
> I made a quick fix, however I'll make a refactoring when the time permits. Also code is not readable and more complicated than necessary.
> 
> ### Status
> * [x]  READY
> 
> ### How to verify this change
> I modified the tests and add the corresponding spacing.
> 
> ### Additional notes
> You can check the corresponding TDK writing rule about the numbers in
> 
> https://www.tdk.gov.tr/icerik/yazim-kurallari/sayilarin-yazilisi/
> 
> point **#2** . For instance
> 
> ```
> 21 = yirmibir is wrong, the correct writing is yirmi=20 bir=1
> ```
> 
> Otherwise `1514` would be `binbesyuzondort` , definitely we don't have such a compounding rule in Turkish and we don't have such word compounds in our lexicon.

Moreover the decimal mark in Turkish is "virgül", not "nokta". The use of this function will be more in accounting entries and especially in the ErpNext that we use so spelling should be monetary and daily use. Regarding code complexity, I have no comment as I am not a full time developer myself.

**Comment by DuyguA** [comment]
1. Why is the default use is legal use? It's just a subdomain of written language, that's it. What is special about it?
2. Well, I think making a general purpose number parser makes more sense which is supposed to have spaces. Then ones who want to adopt to different domains such as finance, banking, legal or medicine can just delete the spaces. Deleting a space is easy, but if a number string has no spaces at all basically that string is useless other than the legal domain.

**Comment by emregeldegul** [comment]
[toofun666](https://github.com/toofun666) If desired, the spaces in between can be deleted. But breaking down the whole word is more difficult.

I also use it for financial transactions and am having problems. All tests have spaces, we have to add spaces.

**Comment by toofun666** [comment]
I totally agree

Tufan Kaynak
Framras A.Ş.

**Pull request closed without merging**
