### PR TITLE
Add gender and morphological cases support for Ukrainian

### PR DESCRIPTION
**Pull request by kant2002**
Added two parameters: gender and case
gender can accept either 'masculine' (default)  or 'feminine' case can accept either 'nominative' (default) or
'genitive','dative','accusative','instrumetnal','locative' and 'vocative'.

This parameters now working only for to='cardinal'

### Changes proposed in this pull request:

* Add ability optionally specify gender when convert to text
* Add ability optionally specify case when convert to text

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

Personally I use this one website https://vshkole.in.ua/vidminiuvannia-chislivnikiv/

I can lookup at more interesting English sources, but it will take time. Also I will try ask for help from local NLP community if that's helpful.

### Additional notes

Slavik languages can have varying forms for words based on grammatic case and gender, so if attempt to convert numbers embedded in the sentence accounting for the form is required. I assume that it's responsibility of the caller to properly identify case and gender of related words.

### CODE REVIEW

**Comment by kant2002** [comment]
@mrodriguezg1991 can I bring your attention to this PR? Do you think this is valuable addition?

**Comment by kant2002** [comment]
I reformat source code

**Comment by kant2002** [comment]
I reformat tests. Did not realize that I should check them, I cannot replicate setup locally, since I use venv and it create false positives for me somehow.

**Comment by kant2002** [comment]
What's my next steps? I see coverage setting go down only in Vietnamese which I did not touch. Is this some infra problem?

**Review by mrodriguezg1991 — APPROVED** [review]

**Pull request merged**
