### PR TITLE
[IMP] Adds ES_CO and ES_VE support. 

### PR DESCRIPTION
**Pull request by 10537**
[ADD] Adds file ES_CO
[ADD] Adds file ES_VE
[UPD] Update name class for both files.

### CODE REVIEW

**Comment by hsoft** [comment]
Thanks @10537 for this PR. I see a lot of code duplication between your two new units and `lang_ES.py`. Do you think that this PR could be reworked to minimize that duplication?

**Comment by 10537** [comment]
Hello @hsoft, Yes, no problem!

**Comment by erozqba** [comment]
Hello @10537, thanks a lot for this PR. I think you also need to include some modifications to the file "num2words/__init__.py" in order to made this two new classes available. Looking at the tests, it will be great if we can add some tests in the test directory for ES, ES_CO, and ES_VE.

**Comment by 10537** [comment]
Hello @erozqba, I've did the changes please review and tell me if you found some new ;)

**Comment by erozqba** [comment]
Hello @10537 
It looks way better! Thanks for taking the time to add the tests. 
I have found some time to propose you some changes and correct another related bug, check the PR https://github.com/savoirfairelinux/num2words/pull/64 that I have created only to share with you some changes. The PR #64 is only to share with you some suggestions and will not be merged, all discussions will take place in this PR #60.

**Comment by 10537** [comment]
Hello @erozqba Please, close this PR, I will do a new PR with the fixes.

**Comment by 10537** [comment]
Hello @erozqba Pelase close #60, I did a new Pull request with all changes.

**Pull request closed without merging**
