### PR TITLE
[tr] return Turkish 0 ordinal and cardinal

### PR DESCRIPTION
**Pull request by cyriaka90**
### Changes proposed in this pull request:

* 0 (cardinal) -> sıfır
* 0 (ordinal) -> sıfırıncı

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

*Fill out this section so that a reviewer can know how to verify your change.*

### Additional notes

fixes https://github.com/savoirfairelinux/num2words/issues/346

*If applicable, explain the rationale behind your change.*

### CODE REVIEW

**Review by DuyguA — APPROVED** [review]

**Comment by cyriaka90** [comment]
Any updates here? :)

**Comment by mromdhane** [comment]
@cyriaka90 you use the API only with script right? 
With the command line, the library is not working with Turkish language
`num2words 0 -l tr` gives `'Num2Word_TR' object has no attribute 'str_to_number'`

**Comment by cyriaka90** [comment]
Thanks for your feedback! Somehow num2words isn't working with the command line for me :/ so yes, I use it only via script.

Would adding

```
    def str_to_number(self, value):
        return Decimal(value)
```

to lang_TR.py solve the problem?

**Comment by mromdhane** [comment]
@cyriaka90 Yes you can do it, Thank you

**Comment by cyriaka90** [comment]
@mromdhane I updated the PR - does Turkish now work with the command line?

**Comment by mromdhane** [comment]
@cyriaka90 yes ! I merge it
Thank you

**Review by mromdhane — APPROVED** [review]

**Comment by cyriaka90** [comment]
Thank you!! :)

**Pull request merged**
