### PR TITLE
Fix several issues with num2words in Arabic

### PR DESCRIPTION
**Pull request by Jeronymous**
There are several issues with Arabic language: https://github.com/savoirfairelinux/num2words/issues?q=is%3Aissue+is%3Aopen+arabic

Some previous work was never merged (and got outdated): https://github.com/savoirfairelinux/num2words/pull/404

This PR fixes:
* https://github.com/savoirfairelinux/num2words/issues/390
* https://github.com/savoirfairelinux/num2words/issues/391
* https://github.com/savoirfairelinux/num2words/issues/392
* https://github.com/savoirfairelinux/num2words/issues/393
* https://github.com/savoirfairelinux/num2words/issues/394
* https://github.com/savoirfairelinux/num2words/issues/403 (2nd point: the results do not change after calling conversion to ordinal)
* https://github.com/savoirfairelinux/num2words/issues/511

also a bug on French:
* https://github.com/savoirfairelinux/num2words/issues/509

This PR does not fix (yet?)
* https://github.com/savoirfairelinux/num2words/issues/403 (some ordinals do not appear)

### CODE REVIEW

**Comment by Jeronymous** [comment]
@mrodriguezg1991 Is there somebody who could review this?

**Comment by mrodriguezg1991** [comment]
> @mrodriguezg1991 Is there somebody who could review this?

Hello, thanks for your contribution, can you update your code to pass flake8 validation ??

**Comment by Jeronymous** [comment]
> Hello, thanks for your contribution, can you update your code to pass flake8 validation ??

@mrodriguezg1991 Thanks for spotting. Code formatting issues are fixed now.

**Comment by mrodriguezg1991** [comment]
@Jeronymous can you pull the master branch in your PR?, because it does not let me merge because the PR is behind

**Comment by Jeronymous** [comment]
@mrodriguezg1991 Sure. Merged

**Review by mrodriguezg1991 — APPROVED** [review]

**Comment by Jeronymous** [comment]
Thanks for merging @mrodriguezg1991 

Note that these issues could be closed (we forgot to mention them in commit messages, and I don't have permissions to close them):
* #390 
* #391 
* #392

**Pull request merged**
