### PR TITLE
Add `fr_DZ` locale

### PR DESCRIPTION
**Pull request by piranna**
This pull-request add support for the `fr_DZ` locale including currency. It also clean up french locales by subclassing `fr_CH` (swiss french) from `fr`, and fix a bug allowing to give `float` numbers to `Num2Word_Base.to_splitnum()` method. The pull-request also has tests for the new locale.

### CODE REVIEW

**Comment by erozqba** [comment]
Hi @piranna 
Thanks for taking the time of make this PR, could you make this compatible with Python 3?

**Comment by piranna** [comment]
> Thanks for taking the time of make this PR, could you make this compatible with Python 3?

I though it was Python 2 code, in fact is what we use at work (don't ask...). I'll try to do it, it shouldn't be difficult. Any advice for it?

**Comment by piranna** [comment]
Ok, fixed, it was a un-parenthesed `print` statement, now tests pass both on Python 2 and Python 3 :-)

**Comment by erozqba** [comment]
Thanks for your great contribution!

**Comment by erozqba** [comment]
@piranna could you update the file README.rst so the new locale is present?

**Comment by piranna** [comment]
> Thanks for your great contribution!

You are welcome :-) When could it be published in PyPi?


> @piranna could you update the file README.rst so the new locale is present?

[Done](https://github.com/savoirfairelinux/num2words/pull/88/)

**Pull request merged**
