### PR TITLE
Remove dupplicated line in lang_PT_BR

### PR DESCRIPTION
**Pull request by israelst**
### Changes proposed in this pull request:

* Remove an unnecessary condition

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

No behavior has been changed. To validate it, we just need to run the tests.

### Additional notes

The line within "if block" does the exact same thing that the line that follows it.

### CODE REVIEW

**Review by erozqba — APPROVED** [review]

**Comment by mromdhane** [comment]
@israelst can you check the coverage, please

**Comment by israelst** [comment]
@mromdhane The coverage hasn't decreased because I added code without tests; instead, I deleted useless code that was counted as covered lines. So, I think that it is safe to ignore the coverage warning this time. ;)

**Comment by mromdhane** [comment]
@israelst you can't add a test to resolve the coverage, please

**Comment by israelst** [comment]
@mromdhane, I've removed some useless and uncovered lines to increase the coverage and fix the CI.

**Review by mromdhane — APPROVED** [review]

**Comment by mromdhane** [comment]
@israelst can you update your branch with master, please
it's ready to be merged

**Comment by israelst** [comment]
@mromdhane, @erozqba has merged from master.

**Pull request merged**
