### PR TITLE
Adding Language Support for Telugu / Bug Fix in Kannada

### PR DESCRIPTION
**Pull request by venu1807**
### Changes proposed in this pull request:

* Add language support for Telugu
* Bug Fix in Kannada concerning currencies

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change
Telugu is not supported yet.
Kannada currencies were not included.

### CODE REVIEW

**Comment by venu1807** [comment]
What do I need to do to pass the coverage test? Please help.

**Comment by mariaS210** [comment]
Hi @venu1807! For coverage, there's a folder with tests: https://github.com/savoirfairelinux/num2words/tree/master/tests
You will need to add a new test file for Telugu and a test case for Kannada (here: https://github.com/savoirfairelinux/num2words/blob/master/tests/test_kn.py) (so that the coverage doesn't drop, and you can check your fix).  
A test simply inherits TestCase and has a test_ method(s) and checks that some numbers are as expected.
Make sure to test the corner cases where Telugu has special handling. Also, make sure to test that years and currency are properly generated.
You can take a look at other tests, for ideas, like the english test: https://github.com/savoirfairelinux/num2words/blob/master/tests/test_en.py
It helps to setup Coveralls and Travis on your forked repo if you want to check coverage as you're writing tests.
Hope this helps.

**Comment by sarahberanek** [comment]
> Hi @venu1807! For coverage, there's a folder with tests: https://github.com/savoirfairelinux/num2words/tree/master/tests
> You will need to add a new test file for Telugu and a test case for Kannada (here: https://github.com/savoirfairelinux/num2words/blob/master/tests/test_kn.py) (so that the coverage doesn't drop, and you can check your fix).
> A test simply inherits TestCase and has a test_ method(s) and checks that some numbers are as expected.
> Make sure to test the corner cases where Telugu has special handling. Also, make sure to test that years and currency are properly generated.
> You can take a look at other tests, for ideas, like the english test: https://github.com/savoirfairelinux/num2words/blob/master/tests/test_en.py
> It helps to setup Coveralls and Travis on your forked repo if you want to check coverage as you're writing tests.
> Hope this helps.

Hi Maria,
there is already a test file for Telugu in Venus pull request: https://github.com/savoirfairelinux/num2words/blob/a2900faccf4922cf6c0be863fe0ddb4292ec40b8/tests/test_te.py

**Comment by mariaS210** [comment]
> 
> Hi Maria,
> there is already a test file for Telugu in Venus pull request: https://github.com/savoirfairelinux/num2words/blob/a2900faccf4922cf6c0be863fe0ddb4292ec40b8/tests/test_te.py

Ah, my bad! I did not look in the pull request. Then I guess https://coveralls.io/builds/24375365/source?filename=num2words/lang_TE.py shows you which lines are not covered in lang_TE.py

**Comment by sarahberanek** [comment]
Hi all,
anything else needs to be done here to get this approved?

**Comment by pierreduchemin** [comment]
> Hi all,
> anything else needs to be done here to get this approved?

No, sorry for the delay

**Pull request merged**
