### PR TITLE
Correction of French ordinal numbers, and add support for feminine and plural.

### PR DESCRIPTION
**Pull request by Linekio**
### Changes proposed in this pull request:

- Correction of French ordinal numbers, and add support for feminine and plural.
Example:
>num2words(1, lang="fr", to="ordinal", feminine=True, plural=True)
>'premières'
- Removing the useless comment line 71: "mille unième" and "millième" are the good forms.
-----------------
- Correction des nombres ordinaux français, et ajout du support pour le féminin et le pluriel.
Exemple:
>num2words(1, lang="fr", to="ordinal", feminine=True, plural=True)
>'premières'
- Suppression du commentaire inutile : "mille unième" et "millième" sont les bonnes formes.

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

Test with lang="fr" and to="ordinal" or "ordinal_num"

### Additional notes

Sources:
[http://www.academie-francaise.fr/abreviations-des-adjectifs-numeraux](http://www.academie-francaise.fr/abreviations-des-adjectifs-numeraux)
[http://www.langue-fr.net/spip.php?article239](http://www.langue-fr.net/spip.php?article239)

### CODE REVIEW

**Comment by erozqba** [comment]
@Linekio thanks a lot for this contribution! I will review it as soon as I have some free time.
I'm actually concerned with the support for the same behaviour in other languages if needed and on the terminal command line.

**Comment by erozqba** [comment]
@Linekio Could you rebase your branch and solve the conflicts? Could you also add some other tests to cover the missed lines [here]( https://coveralls.io/builds/20649624/source?filename=num2words%2Flang_FR.py) ?
Please also check the issue https://github.com/savoirfairelinux/num2words/issues/221 and the comments. 
I will love to have this on num2words, but we need to make sure that this is supported also from the command line, so please provide some examples of how to tests this from the comand line too.

**Comment by Linekio** [comment]
Should I change the arguments in relation to the zenoganther suggestion ? https://github.com/savoirfairelinux/num2words/issues/221

**Comment by erozqba** [comment]
@Linekio, I will let that decision to you. I just want to point you to this discussion about a similar subject so you can take it into consideration when implementing these changes.
I'm really more concerned with the compatibility of these changes with the current features like the command line, and other languages and the missing lines on the tests.

**Comment by erozqba** [comment]
@Linekio any chance of adding tests and rebasing this branch? If you will do it, please open a new PR.

**Pull request closed without merging**
