### PR TITLE
[ES] Added missing accents ("dieciséis", "dólar", "dólares", "veintiún"), improved currency gender handling, fixed pound cent names

### PR DESCRIPTION
**Pull request by gonsalet**
### Changes proposed in this pull request:

* 'lang_ES.py':
  - orthography fixes: Added missing accents "dieciséis", "veintiún", "dólar", "dólares".
  - currency fixes:
    - Fixed pound cent names ("penny"->"penique", "pence"->"peniques").
    - Improved currency gender handling:
      - Separated handling of the genders of the "dollars" part and the "cents" part (each part can have its own gender).
      - Added handling for feminine hundred numbers ("doscientas libras", "trescientas libras"...).
      - Fix: Now "veintiuna", "treinta y una"... are used for feminine currencies, instead of "veintiún", "treinta y un"... (source: https://www.rae.es/dpd/una , section 2.2).
      - Added 'TRY' and 'ITL' to feminine currency list CURRENCIES_UNA.
      - Created feminine "cents" list CENTS_UNA.
    - Updated/fixed error messages in line with 'base.py'.
* 'test_es.py':
  - Updated with the new correct accents "dieciséis", "veintiún", "dólar", "dólares".
  - Updated with the new correct penique/peniques names.
  - Updated feminine currency examples with correct forms ("una lira", "veintiuna liras", "ochenta y una liras", "trescientas cincuenta liras").
  - Added test covering specifically new fix penny->penique.
  - Added test covering specifically new feminine "cents" handling (81.21, 'ochenta y una libras con veintiuna piastras').
  - All other code changes are already covered in existing tests.
* 'bin/num2words': Fixed accent in Spanish examples ("centimos"->"céntimos"), thus making the example consistent with actual current behaviour (not affected by this pull request).
* 'README.rst': Fixed accent in Spanish command line examples ("centimos"->"céntimos"), thus making the example consistent with actual current behaviour (not affected by this pull request).

### Status

- [X] READY
- [] HOLD
- [] WIP (Work-In-Progress)

### How to verify this change
```
>>> from num2words import num2words
>>> num2words('16', lang='es')
'dieciséis'
>>> num2words('1', lang='es', to='currency', currency='USD')
'un dólar con cero centavos'
>>> num2words('16', lang='es', to='currency', currency='USD')
'dieciséis dólares con cero centavos'
>>> num2words('21', lang='es', to='currency', currency='CAD')
'veintiún dólares con cero centavos'
>>> num2words('2.00', lang='es', to='currency', currency='GBP')
'dos libras con cero peniques'
>>> num2words('2.01', lang='es', to='currency', currency='GBP')
'dos libras con un penique'
>>> num2words('350.90', lang='es', to='currency', currency='GBP')
'trescientas cincuenta libras con noventa peniques'
>>> num2words('21.01', lang='es', to='currency', currency='TRY')
'veintiuna liras con un kuruş'
>>> num2words('21.01', lang='es', to='currency', currency='ITL')
'veintiuna liras con un céntimo'
>>> num2words('21.01', lang='es', to='currency', currency='EGP')
'veintiuna libras con una piastra'
```
```
>>> from num2words import num2words
>>> num2words('-12', to='ordinal', lang='es')
[...]
TypeError: El número negativo -12 no puede ser tratado como un ordinal.
>>> num2words('-12.3456', to='ordinal', lang='es')
[...]
TypeError: El float -12.3456 no puede ser tratado como un ordinal.
>>> num2words('100000000000000000000000000000000000000000000', lang='es')
[...]
OverflowError: abs(100000000000000000000000000000000000000000000) deber ser inferior a 1000000000000000000000000000.
```
```
$num2words --help
  num2words: convert numbers into words.
  [...]
  $num2words 2.14 -l es --to currency
  dos euros con catorce céntimos
```
### Additional notes

This PR includes the fixes proposed in currently open pull request https://github.com/savoirfairelinux/num2words/pull/291 by @ekbrown

The added accents are the correct orthography. These words were not correct without the added accents. Orthography checked against official Diccionario de la lengua española ( https://dle.rae.es/ ).

The pound cents "penny" and "pence" were untranslated or inconsistently translated in several parts of the code. Checked that the correct "penique" and "peniques" are now used throughout.

Feminine currency handling is now correct, with independent handling of the "dollars" part and the "cents" part of the currency. Rules checked against official Diccionario panhispánico de dudas ( https://www.rae.es/dpd/una , section 2.2 ). 

Pull request checklist
General
    Can the branch be merged automatically? Yes.
Testing
    Do the unit tests pass? Yes.
Adding new code
    Is the code PEP8 compliant? Yes.
    Is the code covered by tests? Yes.

### CODE REVIEW

**Comment by gonsalet** [comment]
Hi https://github.com/erozqba, I'm not sure who to ask for a review.

I think this is a small but useful fix for Spanish, since it fixes the orthography of a basic number (16, from "dieciseis" to "dieciséis").

I've followed the steps in CONTRIBUTING, and I can take any additional steps I might have missed.

**Comment by erozqba** [comment]
@gonsalet I think your changes are good!

I don't know why the test and coveralls have not run and the new maintainers at Savoir Faire Linux removed me from the list of reviewers with write access, so I cannot approve your PR. :sob:

**Comment by gonsalet** [comment]
Thanks @erozqba!

I guess I'll try to contact Savoir Faire Linux to see if a current maintainer can check this.

**Comment by gonsalet** [comment]
@support-savoirfairelinux anyone who could review this pull request? Thanks!

**Comment by gonsalet** [comment]
@mromdhane anyone who could review this pull request? Thanks!

**Comment by gonsalet** [comment]
@mrodriguezg1991 anyone who could review this pull request? I guess there's a lot of maintenance to be done on this project, so I understand that this pull request might not be the highest priority, but I'm around in case this pull requires any additional steps. Thanks in any case!

**Comment by mrodriguezg1991** [comment]
@gonsalet There are some issues with the CI to be able to merge new pull request, I am currently waiting for access in order to be able to maintain the project, as soon as all the issues are solved, i will be working on answering all requests.
Thanks for your input on the project

**Review by mrodriguezg1991 — APPROVED** [review]

**Pull request merged**
