### PR TITLE
Added pt_PT

### PR DESCRIPTION
**Pull request by hmrodrigues**
Added Portuguese (from Portugal)

### CODE REVIEW

**Comment by erozqba** [comment]
Hello, @hmrodrigues thanks for taking the time to make this PR.

I will suggest naming it simply 'pt', no need for 'pt_PT'. You could probably make a refactoring of the existing pt_BR to make the class pt_BR inherited from pt.

You will need to add some tests and to update the readme file too.

Thanks a lot!

**Comment by ventilooo** [comment]
@hmrodrigues any update ?

**Comment by maelp** [comment]
Will this branch be merged ?

**Comment by erozqba** [comment]
This was already implemented on https://github.com/savoirfairelinux/num2words/pull/198

**Pull request closed without merging**
