### PR TITLE
Add support of Ukrainian language (UA), fix support of UAH currency

### PR DESCRIPTION
**Pull request by artemrizhov**
### Changes proposed in this pull request:

* Add support of Ukrainian language (UA)
* Fix support of UAH currency for Russian language (RU)

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

The changes are covered by tests which are passing successfully. Ukrainian language is very similar to Russian, so the files are just copies of `*_ru.py` with small improvements.

### CODE REVIEW

**Comment by erozqba** [comment]
@artemrizhov thanks a lot for taking the time to contribute with this project. 
I will need your help here. I don't speak Ukrainian so I don't know what are the differences between your implementation and the implementation on **lang_uk.py**. I can see the tests are different and that the proper code for the Ukrainian language it's UA and not UK which I learn after looking at your PR.

So I need your help consolidating the Ukrainian language into only one implementation.
Thanks a lot in advance.
:pray:

**Comment by ahlinc** [comment]
@erozqba Accordingly to https://www.iban.com/country-codes it's a correct idea to change the Ukrainian language code from UK to UA, but it would be good to have some deprecation warning with automatic loading UA lang in case of UK and retention possibility to use the UK code for some period of time.

**Comment by erozqba** [comment]
@ahlinc
Sure, we should have some deprecation warning, and load UA lang in case of UK, about the possibility to use the old implementation I'm less sure if the new implementation is an improvement of the first one, why we should keep both?
@artemrizhov will you be able to consolidate the implementations?

**Comment by ahlinc** [comment]
@erozqba If you don't mind as @artemrizhov doesn't respond I can make discussed changes for this PR when I'll have a time soon.

**Comment by artemrizhov** [comment]
Sorry, I've missed the notifications from this thread.
I did not know uk is Ukraine. I thought uk means United Kingdome)))
I'll check which one is better and try to merge these two languages into one if it makes sense.

**Comment by ahlinc** [comment]
@artemrizhov Great to get the update from you.
I think it makes sense to conform to standard abbreviation and merge to the `uk` but leaving the `ua` for some time with showing python DeprecationWarning in case of the `ua` usage.
Also please look onto my question here: https://github.com/savoirfairelinux/num2words/pull/301/files/0b6f5167fec7626a3f44d0d582661bb4e5f1e832#diff-07f8a4549bc5d02ad2d8c1a9d5b54578R95

**Comment by mromdhane** [comment]
@artemrizhov are you still working on it, please? Also, there are some conflicts.

**Comment by wildsurfer** [comment]
We need this! :)

**Comment by rostyslav80** [comment]
@mromdhane According to [ISO 639-2](https://www.loc.gov/standards/iso639-2/php/code_list.php), `uk` is a correct code for Ukrainian language, not `ua`, as suggested in this PR. For this reason, this PR can be closed.

**Comment by mromdhane** [comment]
@artemrizhov @rostyslav80  we don't need to merge these two languages into one? if not I will close this PR

**Comment by rostyslav80** [comment]
> @artemrizhov @rostyslav80 we don't need to merge these two languages into one? if not I will close this PR

@mromdhane Yes, you can close it.

**Comment by mromdhane** [comment]
Already exist on **lang_UK**

**Pull request closed without merging**
