### PR TITLE
add ru lang into supported languages

### PR DESCRIPTION
**Pull request by alexpantyukhin**

### CODE REVIEW

**Comment by hsoft** [comment]
Thanks @alexpantyukhin , much appreciated. That's a sizeable chunk of code to review and I lack time these days, so it might take a while for the merge to happen, but it will be done, eventually.

Don't hesitate to poke if it doesn't...

**Comment by alexpantyukhin** [comment]
You are welcome! Actually it's based on the Poland lang and maybe it would be good to extract common functions in the some common file.

**Comment by hsoft** [comment]
I *will* review this, it's just that I'm really busy these days at work.

**Comment by alexpantyukhin** [comment]
Hello.
what about this pull request?

**Comment by hsoft** [comment]
Pushed on `master`. Thanks again @alexpantyukhin ! I am very sorry it took so long for me to review this.

**Comment by hsoft** [comment]
To be sure, I didn't review all russian strings. I simply tested a couple of test outputs. I don't speak russian. I'll trust that they're correct, and if they're not, someone else will correct them.

**Pull request closed without merging**
