### PR TITLE
Updated spanish translations

### PR DESCRIPTION
**Pull request by cesarizu**
This commit adds correct ordinal numbers for spanish up to 10e18 - 1.

### CODE REVIEW

**Comment by hsoft** [comment]
Oh, sorry for the delay, I forgot about that PR entirely!

I'm unfortunately unable to review this PR because I don't know spanish, so I'd be inclined to accept it by default because it looks good. @carlosblanco , could you take a look please?

(if he doesn't in a few days, I'll just merge it. don't hesitate to poke me again if I don't)

**Comment by carlosblanco** [comment]
Sure I can. I'll review the code when get to my PC. Looking at the strings, they look wrong for the low_numwords values for the 20's. They should be "veinti..." and not "vienti..."

**Comment by cesarizu** [comment]
Thanks for the correction. I didn't realize that error (it was already present on the original file). I've fixed those strings and updated this pull request.

**Comment by hsoft** [comment]
Yay for 6-eyed reviews with two of them not understanding spanish! :)

**Comment by wtrevino** [comment]
I just closed a pull request that changed grave accents to accute, cesarizu's pull request is better and more complete, I can also confirm last commit changes are correct! (fellow spanish speaker).

**Comment by hsoft** [comment]
Awesome, thanks everyone. I'll make a new PyPI release soon. There's a much of minor improvements having been contributed since the last release.

**Pull request merged**
