### PR TITLE
Added support for Dutch language (NL)

### PR DESCRIPTION
**Pull request by olix20**
added lang_NL.py file and updated __init__.py to reflect this.

### CODE REVIEW

**Comment by erozqba** [comment]
@olix20 Thanks a lot for your PR.
Could you provide a separate test file like the one you can find in `test` directory?
Could you remove commented lines of code that are not in use?

Thanks again for taking the time to make this contribution!

**Comment by olix20** [comment]
Hey @erozqba 
no problem, i needed a num2word for one of my own project and couldn't find anything suitable; hope this helps someone save some time :) Thanks for maintaining it! 

Added tests/test_nl.py
About comments, there weren't many comment lines to begin with but removed one anyway.

**Comment by toofun666** [comment]
Hi there,
don't forget to include the new languages in the Readme file.

**Comment by erozqba** [comment]
@toofun666 great catch! 
@olix20 please add the new language in the Readme file!

Thanks.

**Comment by erozqba** [comment]
@olix20 Could you make a rebase over the last changes merged in master to fix the conflict?

**Comment by erozqba** [comment]
:+1:

**Comment by erozqba** [comment]
Hi @olix20, sorry for asking this again but I just merge one other PR.
@olix20 Could you make a rebase over the last changes merged in master to fix the conflict?

**Comment by olix20** [comment]
resolved conflicts, @erozqba appreciate if you could merge it soon.

**Comment by erozqba** [comment]
:+1:

**Pull request merged**
