### PR TITLE
Fix bugs in the float precision and the currency, increase test coverage

### PR DESCRIPTION
**Pull request by erozqba**
Ref: issue #112 #113 #119

### CODE REVIEW

**Comment by erozqba** [comment]
Hello @isnani, @olix20 @mbcosta @bblaz 
I was adding some tests for 'es' and finish modifying the precision to find it more dynamically, this change has impacted your tests, so I modified the test that you have written. 
Could you please check this PR and let me know if there are some things that should not be merged?

**Comment by bblaz** [comment]
Hi @erozqba,

It's ok on test_sl.

Best regards, etc
Blaž

**Comment by mbcosta** [comment]
:+1:

**Comment by erozqba** [comment]
Thanks, @bblaz and @mbcosta for your feedback!

**Pull request merged**
