### PR TITLE
Add INR for en_IN. Default to INR for ‘currency’. Add test case

### PR DESCRIPTION
**Pull request by patelnav**
### Changes proposed in this pull request:

* Add currency "INR" to en_IN.
* Override to_currency to use "INR" by default when using "en_IN"

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

New test-case has been added to verify change, so run test!

### Additional notes

Strangely enough @chintal happened to add INR to en_EUR just now!
I happened to make practically the same change in en_IN. I suppose that works if you want to use Rupees but with standard billion/million notation rather than the [Indian number system](https://en.wikipedia.org/wiki/Indian_numbering_system).

### CODE REVIEW

**Comment by patelnav** [comment]
@erozqba if you don't mind reviewing.

**Comment by chintal** [comment]
@patelnav The addition to en_EU trickles down appropriately to en_IN, allowing you to use INR in any locale descendent from en_EU. If you use it with EU or one of the others you will get millions, billions. If you use it with en_IN you will get lakhs, Crores. This will fail at 1000 Crores and beyond, however.

**Comment by patelnav** [comment]
@chintal: ah! didn't know en_IN would inherit the currency from en_EU.

Will close this merge request. Thanks.

**Comment by patelnav** [comment]
I was getting confused because the pip version doesn't have @chintal's commit yet. 
@erozqba please let us know when you push the release.

**Pull request closed without merging**
