### PR TITLE
Add support to pt_BR language

### PR DESCRIPTION
**Pull request by filwaitman**
This one adds support to Brazilian Portuguese language (maybe Portuguese itself, but I would need a reviewer from Portugal to ensure everything is the same).

I've implemented some tests as well. Please check it out.

If something is missing, please let me know.

### CODE REVIEW

**Comment by erozqba** [comment]
Thanks @filwaitman, much appreciated. Could you fix the conflicts ? It will be more easy to make the review.

**Comment by mazulo** [comment]
Hey @filwaitman please fix these conflicts. I really want to use your contribution to this project :smile:

**Comment by hsoft** [comment]
I've tried to proceed with the merge, but when I run the tests (thanks @filwaitman for this test suite), I get these errors:

```
======================================================================
ERROR: test_cardinal_float (tests.test_pt_BR.Num2WordsPTBRTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdupras/src/num2words/tests/test_pt_BR.py", line 84, in test_cardinal_float
    self.assertEquals(num2words(Decimal('1.01'), lang='pt_BR'), 'um ponto zero um')
  File "/home/vdupras/src/num2words/num2words/__init__.py", line 62, in num2words
    return converter.to_cardinal(number)
  File "/home/vdupras/src/num2words/num2words/lang_PT_BR.py", line 133, in to_cardinal
    result = super(Num2Word_PT_BR, self).to_cardinal(value)
  File "/home/vdupras/src/num2words/num2words/base.py", line 93, in to_cardinal
    return self.to_cardinal_float(value)
  File "/home/vdupras/src/num2words/num2words/base.py", line 125, in to_cardinal_float
    curr = int(post[i])
ValueError: invalid literal for int() with base 10: '.'

======================================================================
ERROR: test_cardinal_float_negative (tests.test_pt_BR.Num2WordsPTBRTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdupras/src/num2words/tests/test_pt_BR.py", line 92, in test_cardinal_float_negative
    self.assertEquals(num2words(Decimal('-2.34'), lang='pt_BR'), 'menos dois ponto três quatro')
  File "/home/vdupras/src/num2words/num2words/__init__.py", line 62, in num2words
    return converter.to_cardinal(number)
  File "/home/vdupras/src/num2words/num2words/lang_PT_BR.py", line 133, in to_cardinal
    result = super(Num2Word_PT_BR, self).to_cardinal(value)
  File "/home/vdupras/src/num2words/num2words/base.py", line 93, in to_cardinal
    return self.to_cardinal_float(value)
  File "/home/vdupras/src/num2words/num2words/base.py", line 126, in to_cardinal_float
    out.append(str(self.to_cardinal(curr)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 2: ordinal not in range(128)

----------------------------------------------------------------------
Ran 21 tests in 0.024s
```

The second failure seems easy enough to fix, but the second failure is caused, I think, by the recent change introduced by [995c153d47149a67299e3049ebc02338f2ff7c3a], authored by @isnani . Now, I have to admit, I'm not too sure what's going on, why this change was introduced and why it breaks things here.

I don't have the time to look into it right now. I'll come back to this later. But in the meantime, if we could have insight from @isnani about the reason for the `base.py` change in this commit referenced above (which, unfortunately, isn't part of the commit log), it would be great.

**Comment by hsoft** [comment]
To be clear: The test suite passes when we run it strictly in @filwaitman's branch (that is, without rebasing). This means that recent changes in `master` broke @filwaitman's test suite. Was the test suite flaky or were there regressions introduced in `master`? that is the question.

**Comment by filwaitman** [comment]
Hi folks!

Sorry for the delay on solving this conflict, I'm in a hurry.
@erozqba, @mazulo: actually I've tried to merge supposing it would be simple. However, it didn't.  :laughing: 
@hsoft in fact, I need to investigate what's exactly the change that is causing this broken test.

I'm checking it out Saturday. @isnani if you have some clue please let me know!  :smile:

**Comment by erozqba** [comment]
Hi folks!
There was a regression introduced by [995c153], after solve the regression all tests pass.

**Comment by filwaitman** [comment]
Thanks for that, @erozqba!  =]

**Pull request merged**
