### PR TITLE
Created Portuguese from Portugal

### PR DESCRIPTION
**Pull request by afonsojramos**
### Changes proposed in this pull request:

* Added PT_PT support

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

Similar to other languages.

### Additional notes

Thought there should be a Original Portuguese version

### CODE REVIEW

**Comment by afonsojramos** [comment]
Will add Test Coverage in the future

**Comment by erozqba** [comment]
@afonsojramos there is already an effort to do the same on https://github.com/savoirfairelinux/num2words/pull/198 with coverage included. Could you contribute with the other PR?

**Comment by afonsojramos** [comment]
Sure!

**Comment by afonsojramos** [comment]
There are some heavy differences though, however he already has testing, which would be easily copied to this PR

**Comment by erozqba** [comment]
@afonsojramos even if there are some differences, you should be able to suggest some improvements and collaborate with it? Do you think this implementation is better than the one on the PR #198 in all aspects? If not, then suggest the improvements you can see on PR #198. I would like to promote collaboration between different developers working on the same feature than choose the work of one of the developers over the other.

**Comment by erozqba** [comment]
@afonsojramos PR #198 get merged, if you have suggestions to do, create a new PR.

**Pull request closed without merging**
