### PR TITLE
Patch for large numbers as strings

### PR DESCRIPTION
**Pull request by H4CKY54CK**
This pull request aims to fix the rounding error when trying to use the library with numbers passed as strings that exceed 30 characters in length.

Currently, passing any number as an integer or a string produce the same result, until the string version exceeds 30 characters in length. `9999999999999999999999999999999` and `'9999999999999999999999999999999'` produce different outputs, and it is clear why this is the case in the output. Using `9999999999999999999999999999999` at the command line also produces the wrong output, because it's being passed as a string.

I don't work with the `Decimal` library very much, but this is what I managed to throw together to fix these issues. I don't know whether how I've done it is necessarily "right" or not, but it _does_ fix the problem, both when using the function or the CLI. By all means, if there is a better way to accomplish what I've done, I'm all ears.

I've tested this on both Windows 10 64 bit, Python 3.8.5 and Ubuntu 20.04 Server for Pi, 64 bit, Python 3.8.5. It also_seems_ to work all the way to the library's own limit (307 `9`s). I obviously haven't verified that the text output is correct, but it _looks_ correct at a glance, at least.

### CODE REVIEW

**Comment by H4CKY54CK** [comment]
I also meant to add that all testing the library via `python setup.py test` was the same, before and after the patch, on both Windows and Ubuntu.

**Comment by H4CKY54CK** [comment]
Added a test.

**Comment by mromdhane** [comment]
@H4CKY54CK  Yes! I can reproduce the issue. I review and test it, can you please update and rebase your branch with master.
Thank you!

**Comment by H4CKY54CK** [comment]
Sorry, I only recently started using `git`, and rebasing is something I'm still not 100% sure how to do. If you tell me the commands, I'll be happy to take care of it immediately.

**Comment by mromdhane** [comment]
@H4CKY54CK  your branch must be base on currrent HEAD. and you should "squasher" your commits into one with a clair message like `[FIX] conversion large numbers as strings`
You can read more about these command `git rebase` , `git squash`
Thank you

**Comment by H4CKY54CK** [comment]
I made a mistake, so please refer to my new PR. Sorry.

**Pull request closed without merging**
