### PR TITLE
add basic farsi support

### PR DESCRIPTION
**Pull request by HKalbasi**
### Changes proposed in this pull request:

* add basic farsi support.

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change
You can check tests if you know Farsi.

### Additional notes
[This](https://discourse.mozilla.org/t/persian-farsi-tts/70498/14) motivates me.

### CODE REVIEW

**Comment by erozqba** [comment]
@HKalbasi could you please, add some tests for the missing lines on the coverage https://coveralls.io/builds/35770814/source?filename=num2words%2Flang_FA.py

**Comment by HKalbasi** [comment]
@erozqba Done.

**Comment by erozqba** [comment]
@HKalbasi has you can see the tests are failing, could you fix them, pelase?

**Comment by HKalbasi** [comment]
Just one of them remains, But I don't know what is the problem and how to solve it. Maybe it is due to python2 problem with unicode?

**Comment by mromdhane** [comment]
@HKalbasi The test failed:

`FAIL: test_ordinal (tests.test_fa.Num2WordsFATest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/savoirfairelinux/num2words/tests/test_fa.py", line 43, in test_ordinal

    'بیست و سوم'

AssertionError: '\xd8\xa8\xdb\x8c\xd8\xb3\xd8\xaa \xd9\x88 \xd8\xb3\xd9\x87\xd9\x85' != '\xd8\xa8\xdb\x8c\xd8\xb3\xd8\xaa \xd9\x88 \xd8\xb3\xd9\x88\xd9\x85`

**Comment by HKalbasi** [comment]
I had seen it. But I don't know what those cryptic characters mean. When I print them those are this:
```
Ø¨ÛØ³Øª Ù Ø³ÙÙ != Ø¨ÛØ³Øª Ù Ø³ÙÙ
```
It seems there is a unicode issue with python2 which I know nothing about them. You did not have the same problem before? For example, for Arabic? Any idea?

By the way, python2 is dead more than one year. Do you still need to check it in the CI?

**Comment by erozqba** [comment]
> I had seen it. But I don't know what those cryptic characters mean. When I print them those are this:
> 
> ```
> Ø¨Û�Ø³Øª Ù� Ø³Ù�Ù� != Ø¨Û�Ø³Øª Ù� Ø³Ù�Ù�
> ```
> 
> It seems there is a unicode issue with python2 which I know nothing about them. You did not have the same problem before? For example, for Arabic? Any idea?
> 
> By the way, python2 is dead more than one year. Do you still need to check it in the CI?

We should probably remove it any time soon, but sadly python 2.7 still continue to be used a lot.

**Comment by HKalbasi** [comment]
> We should probably remove it any time soon

Do I have to do anything else or just wait?

> but sadly python 2.7 still continue to be used a lot.

Yes, but they do not need the latest version of this library.

**Review by mrodriguezg1991 — APPROVED** [review]

**Pull request merged**
