### PR TITLE
Ukrainian language

### PR DESCRIPTION
**Pull request by Sergeyzhol**
Added Ukainian language support

### CODE REVIEW

**Comment by erozqba** [comment]
@Sergeyzhol Thanks for your PR. I will look into this as soon as possible.

**Comment by toofun666** [comment]
Do not forget to include your language in the readme.rst file!

**Comment by Sergeyzhol** [comment]
Re: [savoirfairelinux/num2words] Ukrainian language (#93)



I've made the change in readme.rst. Thanks

**Comment by toofun666** [comment]
The readme.rst update not pushed yet?

**Comment by Sergeyzhol** [comment]
Re: [savoirfairelinux/num2words] Ukrainian language (#93)



@toofun666
I've made changes to files README.rst and __init__.py ,added lang_UK.py and test_uk.py.
My pull request is waiting for push.

**Comment by erozqba** [comment]
@Sergeyzhol this looks like a good start, I will merge it.
Could you please implement `to_currency()`, `to_year()` and `to_cardinal()` in the class Num2Word_UK?

**Pull request merged**
