### PR TITLE
[ADD] num2words: add support to translate some currencies in italian language

### PR DESCRIPTION
**Pull request by primes2h**
### Changes proposed in this pull request:

* Adding support for italian translation of some currencies (to_currency)
* Tests for italian language currencies

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change
```
lang='it'                                                                                     
var1 = '49.95'                                                                                                                                 
var2 = '1.01'                                                                              
b = num2words(var1, lang=lang, to='currency', currency='USD')
print(b)                                                               
d = num2words(var2, lang=lang, to='currency', currency='EUR')
print(d) 
```

### CODE REVIEW

**Comment by mrodriguezg1991** [comment]
@primes2h Hello, can you update this PR with the master branch in order to run the test and review it
Thanks

**Comment by primes2h** [comment]
> @primes2h Hello, can you update this PR with the master branch in order to run the test and review it Thanks

Done, thank you.

**Comment by mrodriguezg1991** [comment]
@primes2h Can yo fix the following to pass flake8 validation in python3.10
 ./tests/test_it.py:54:1: E302 expected 2 blank lines, found 1
  ./num2words/lang_IT.py:203:1: E302 expected 2 blank lines, found 1
Thanks

**Comment by primes2h** [comment]
> @primes2h Can yo fix the following to pass flake8 validation in python3.10
> 
> ```
>  ./tests/test_it.py:54:1: E302 expected 2 blank lines, found 1
>  ./num2words/lang_IT.py:203:1: E302 expected 2 blank lines, found 1
> ```
> 
> Thanks

Done!

**Comment by primes2h** [comment]
@mrodriguezg1991 

All ✔️ now.

**Review by mrodriguezg1991 — APPROVED** [review]

**Pull request merged**
