### PR TITLE
Romanian issues 259

### LINKED ISSUE #259: Romanian language issues:
Some issues:
```
num2words(22000, lang='ro')
'douăzeci și doi mie'
```
should be
```douăzeci și două mii```

For currency, i know the convention is „una” instead of „o”. That's what it is written on the banknotes, „UNA SUTĂ”. 

I'm currently adjusting the result with:
`.replace('o mie', 'una mie').replace('o sută', 'una sută').replace('doi mie','două mii').replace(' ', '')`
(also removing the spaces for financial documents)

_Originally posted by @silvium in https://github.com/savoirfairelinux/num2words/pull/215#issuecomment-499239834_

### PR DESCRIPTION
**Pull request by mariaS210**
### Changes proposed in this pull request:

* 2 has different gender form when in hundreds or thousands area
* currency for 100 and 1000 has `una` instead of `o`, like on banknotes
* 10.000 - 100.000 with increment by 10.000 badly represented

### Status

- [X ] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change
Issues reported: 
Different treatment for 2:
`num2words(22000, lang='ro')`
until now: `douăzeci și doi mie`
from now: `douăzeci și două mii`

Currency for 100 and 1000 has a different form  than years or simply numerals:
`num2words(1000, lang='ro', to='currency')`
until now: `o mie`
from now: `una mie`

10.000 - 100.000 with increment by 10.000 were badly represented: 
`num2words(20000, lang='ro')`
until now: `douăzeci și mie/i`
from now: `douăzeci mii`

### CODE REVIEW

**Comment by mariaS210** [comment]
pet-423398_640
this puppy is sad that pull request is not reviewed

Image by <a href="https://pixabay.com/users/Winsker-31470/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=423398">Winsker</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=423398">Pixabay</a>

**Comment by mariaS210** [comment]
hi @erozqba !
i noticed that i did not implement `pluralize` as defined in http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html and that indeed Romanian has another plural form which i ignored. i have implemented it now.
could you please take another look?
thank you, and sorry for the delay

**Comment by erozqba** [comment]
Thanks a lot for your contribution @mariaS210 and please accept my apologies for all the time it takes to review and merge this :sob:

**Comment by mariaS210** [comment]
> Thanks a lot for your contribution @mariaS210 and please accept my apologies for all the time it takes to review and merge this 😭

no worries @erozqba i had an excuse to search pictures of puppies on the internet 😄

**Pull request merged**
