### PR TITLE
added swedish language including test cases

### PR DESCRIPTION
**Pull request by peternordstrom**
### Changes proposed in this pull request:

* add swedish language support

### Status

- [ X] READY
- [ ] HOLD
- [] WIP (Work-In-Progress)

### How to verify this change

*Check if words look reasonable? Compare to Norweigan.*

### Additional notes

*Swedish rules are very similar to norweigan so it was pretty easy to add this language*

### CODE REVIEW

**Comment by erozqba** [comment]
@peternordstrom could you please, add tests for the missing lines on https://coveralls.io/builds/35506839/source?filename=num2words%2Flang_SV.py#L98? We can't merge the PR if the coverage decreases.

**Comment by peternordstrom** [comment]
@mromdhane, I have updated the code so that it passes all tests now. See if it looks ok to you.

**Review by erozqba — COMMENTED** [review]
@peternordstrom thanks for updating the tests. I forgot to suggest you update the README.md also to include Swedish on the list of languages, could you do it, please.

Any intention to implement `year`, `currency` and `ordinal` ?

**Comment by peternordstrom** [comment]
I updated the Readme now.
I might implement year, currency and numordinal later but for now, this is
what I have time for. And I believe these are the most important
implementations.

Cheers

Peter

**Review by mromdhane — APPROVED** [review]

**Comment by mromdhane** [comment]
@peternordstrom  Thank you to add swedish language and hope to continue the `Not implimented`

**Pull request merged**
