### PR TITLE
Danish language support

### PR DESCRIPTION
**Pull request by fennesz**
Danish is very particular about word splits, endings, and contractions.

### CODE REVIEW

**Comment by hsoft** [comment]
Thanks @fennesz ! Question: is "forty two" in Danish "toogfyrre"? Google translate doesn't seem to tell us so.

**Comment by fennesz** [comment]
Yup! And Google translate says so for me:
https://translate.google.com/#en/da/forty%20two

**Comment by hsoft** [comment]
Oh, yes, I didn't think of trying the opposite. I'll merge it then.

**Comment by hsoft** [comment]
hey, the project has forty-two stars...

**Pull request merged**
