### PR TITLE
fix Polish twenties

### PR DESCRIPTION
**Pull request by cyriaka90**
### Changes proposed in this pull request:

* dziewięćdzisiąt -> dziewięćdziesiąt
(see https://github.com/savoirfairelinux/num2words/issues/277)

### Status

- [x] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

Polish should output dziewięćdziesiąt instead of dziewięćdzisiąt for 90

### Additional notes

Seems to be a typo.

### CODE REVIEW

**Comment by cyriaka90** [comment]
Any updates here? :)

**Comment by cyriaka90** [comment]
@mromdhane do you know why the checks aren't completing after I merged master?

**Comment by egorvavilov** [comment]
Hey, guys
Do you need help with this one? Because it is an issue for 2 years already!)

**Comment by cyriaka90** [comment]
It's really just correcting typos. Don't know why the maintainers didn't take a look yet. :/

**Review by egorvavilov — APPROVED** [review]
All changes to polish version of words are correct
@mromdhane can you include PR into future release?)

**Review by PlusSP — APPROVED** [review]

**Review by PlusSP — APPROVED** [review]
pls accept it

**Comment by PlusSP** [comment]
we need this change, pls merge it

**Review by PlusSP — APPROVED** [review]
pls accept it

**Comment by cyriaka90** [comment]
@mrodriguezg1991 maybe? or @mromdhane?

**Review by PlusSP — DISMISSED** [review]
i approve

**Comment by mrodriguezg1991** [comment]
@cyriaka90 Hello and thanks for the contribution
The test coverage seems to drop with this change, can you add some tests??

**Comment by cyriaka90** [comment]
> @cyriaka90 Hello and thanks for the contribution The test coverage seems to drop with this change, can you add some tests??

It's really odd, since I only changed the spelling and didn't really add anything. But I'll add some tests. :)

**Comment by cyriaka90** [comment]
Test coverage seems to be fine now :)

**Review by mrodriguezg1991 — APPROVED** [review]

**Pull request merged**
