### PR TITLE
[FIX] ISO code for Belarusian language is be, not by.

### PR DESCRIPTION
**Pull request by SkiBY**
### Changes proposed in this pull request:
 ISO code for Belarusian language is be, not by.

### Status

- [X ] READY

### How to verify this change
https://lh.2xlibre.net/locale/be_BY/

### CODE REVIEW

**Comment by SkiBY** [comment]
@mrodriguezg1991 i tried to do my best with the coverage, but still it is marked as decreased -0.08% for most builds.
Could we ignore it?

**Comment by SkiBY** [comment]
@mrodriguezg1991 ?

**Comment by mrodriguezg1991** [comment]
> @mrodriguezg1991 ?

Can you update with the changes on master, i we can see the test coverage status ?

**Comment by SkiBY** [comment]
@

> > @mrodriguezg1991 ?
> 
> Can you update with the changes on master, i we can see the test coverage status ?

just pushed

**Review by mrodriguezg1991 — APPROVED** [review]

**Pull request merged**
