### PR TITLE
FR : Small corrections concerning the plural of millions, milliards,... (#188)

### PR DESCRIPTION
**Pull request by reboutli-crim**
… cents and vingts

### Changes proposed in this pull request:

* Millions, milliards,... prend toujours un  "S" quand on parle de plusieurs millions, milliards même s'ils sont suivis par d'autres chiffres (contrairement à vingt et cent)
* Cent (ou vingt) doit prendre un S s'il est suivi de millions (milliards,..) 

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

I have added some test cases to test my changes. 

### Additional notes

Voir la issus #188 pour les références

### CODE REVIEW

**Comment by erozqba** [comment]
@reboutli-crim Sorry for taking too long on this review but I don't understand what is happening with the test coverage and why it has dropped by more than 1% with your changes. Ideally, we want to increase test coverage and not reduce it. I will try to figure it out this weekend. If you find out the reason and can improve the test coverage that will be really helpful! 
Thanks a lot for your time and contribution.

**Comment by reboutli-crim** [comment]
@erozqba I've noticed that the coverage has dropped but I have really no idea why. The only file I have changed is still 100% covered and I have written test cases to cover my changes. I will check this weekend if I can find an explanation to this.

**Comment by erozqba** [comment]
@reboutli-crim I found some problems with the coverage and this was fixed on `master` branch, we have been included in the tests files on the coverage report which is wrong. Please rebase your branch over `master`.

**Comment by reboutli-crim** [comment]
Done! Should I create a new pull request?

**Pull request merged**
