### PR TITLE
Added Tajik language support

### PR DESCRIPTION
**Pull request by decherd**
### Changes proposed in this pull request:

* Added Tajik language support and tests

### Status

- [X ] READY
- [ ] HOLD
- [] WIP (Work-In-Progress)

### How to verify this change

*All tests pass
*Google translate isn't 100% accurate for Tajik. Tajik is a Persian language but the only one that uses Cyrillic. There isn't a similar language file.
*Trust me.

### CODE REVIEW

**Comment by decherd** [comment]
@mromdhane
Would you mind reviewing this PR? I believe everything should be good with flake8 and test coverage.

**Comment by decherd** [comment]
The code I added for Tajik support is at 100% coverage. None of the checks completed. Are those supposed to run automatically or is a review required first? This is my first pull request. I'm pretty excited to both be contributing to my first open source project and to be adding Tajik language support. I've attempted to make sure I'm not missing anything but if I am just let me know what I need to do. Thanks!

**Comment by mromdhane** [comment]
@decherd Thank you for your contribution  ! we wait for the coverage and the tests after I will review your PR.

**Comment by decherd** [comment]
@mromdhane Is there a typical timeline of when the pull request should be reviewed and merged? Again, this is my first contribution to an open source project and didn't know how long I should be waiting for this. Thanks.

**Comment by mrodriguezg1991** [comment]
@decherd Hello and thanks for your contribution, can you fix your PR to pass the test on python3.10 ?

**Comment by mrodriguezg1991** [comment]
> I've fixed the flake8 errors and run tox locally and everything passes. I've been waiting over a year to see my contributions merged and would love if you could see that happen.

Sorry for the inconvenience, everything should be ok, this changes will be added in a new release soon

**Pull request merged**
