### PR TITLE
Increase test coverage for lang fr*

### PR DESCRIPTION
**Pull request by erozqba**
### Changes proposed in this pull request:

* Fix issues  #116 #121 #127

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

*Review the code changes to check the new tests added and verify that all tests pass in Travis-CI.*

### CODE REVIEW

**Comment by erozqba** [comment]
@ssirois @mdupuis could you check the French tests that I have added?
You are more qualified in French than me! :)

**Comment by ssirois** [comment]
@erozqba here are documents that could help you with your French numbers written in letters:

* http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?t1=1&id=5135
* http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?t1=1&id=3494

on on the general subject of numbers in French:

* http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?T1=nombres&T3.x=0&T3.y=0

I started to _comment_ on your PR, but I think it would be a better idea to send you a PR on your branch.

Let me clone this and send you a PR.

**Comment by ssirois** [comment]
@erozqba hope that #137 helps you. Don't be shy to ask for more if it helps you!

**Comment by erozqba** [comment]
Yes @ssirois, is the same in Spanish and that really bothers me.At the base, this lib is used to write checks, so I don't really know if that is the reason behind this behavior.We should fix this but that will be the subject of another issue because #136 is only to increase the coverage.

So I'm merging this so we could fix the translation problems in other issues.

**Comment by ssirois** [comment]
@erozqba OK. Being an _outsider_, I do not understand what's the value behind having tests that prove the library is wrong but I guess that this could be a strategy to get over the coverage bot minimal requirement **and then** address the issue somewhere else while not being blocked anymore by the test coverage limitation.

Thank you for the clarification.

**Pull request merged**
