### PR TITLE
correction on lang_DE: ordnum, plural and ord form of >= 10**6

### PR DESCRIPTION
**Pull request by isnani**
I am not a German native. But I'm quite sure about the correction I've made.
1. using '.' instead of 'te' as suffix of ordinal number. ex: 23.
2. normally, German use 'en' instead of 'es' for the plural of 'million' so it becomes 'millionen'
3. Ordinal form of number 100, 1000 and so on, it adds 'ste' instead of only 'te'. example: hundertste, tausendste ...

However it needs to be verified.

### CODE REVIEW

**Comment by hsoft** [comment]
Danke! and there's tests too...

I'll review it properly as soon as I have a minute.

**Comment by hsoft** [comment]
The review is taking a lot of time because I'm really busy, I *will* get to it some day...

**Comment by hsoft** [comment]
Hi @isnani , sorry again about the delay for my review. This looks good to me, but I'm a bit uneasy about removing the `ordflag` mecanism without understanding what it was supposed to do. Sure, it doesn't look like it's useful very often (apparently, only for numbers > `10**6`).

I tried to find numbers for which the output would be different without the old flag, but I couldn't. Do you have any idea what could have been the purpose of this flag?

If not, we'll go ahead with its removal and see later if it breaks something, but I'd be much more comfortable merging this if I knew what this flag was about...

**Comment by isnani** [comment]
Hi @hsoft,  that's because I couldn't find the purpose after I changed `to_ordinal` function. It's no longer necessary as it will never be `True`.
Hence, you might first review the change I made in `to_ordinal` function.

**Comment by hsoft** [comment]
Wouldn't the condition be true for numbers that are over `10**6`?

**Comment by hsoft** [comment]
To be clear @isnani : I'm not trying to push the burden of trying to understand this logic yourself. We're in a situation where the original author is not there to explain this logic. Unless we're sure that this flag has absolutely no effect, I'd prefer to leave it there. One day, someone will take the time to properly analyze this behavior.

Until then (or unless you're willing to analyze the effects of that flag further), I'd suggest to change your PR so that we keep the flag so I can merge your improvements.

**Comment by isnani** [comment]
Hi @hsoft , sorry for late response.
Even this flag makes the result incorrect. Have a look at this line in `merge` function:
`if ntext.endswith("e") or self.ordflag:`

That will always be true as you assigned `True` to `ordflag` (in `to_ordinal` function). It means else's clause is unreachable. As the result, ordinal spell of 2000000 is zwei millio**nn**te, instead of the correct one, millio**nen**te.

**Comment by hsoft** [comment]
I'm late too, sorry.

Alright, let's merge it as is. As we can see in #45, this unit has some obvious bugs in it, so the existing code can't be treated as a gold standard.

Thanks again @isnani for your work and patience, merging.

**Pull request merged**
