### PR TITLE
Multitude of corrections of Slovene language

### PR DESCRIPTION
**Pull request by bblaz**
### Changes proposed in this pull request:

* Multitude of correction for Slovene language to increase test coverage

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

The original tests have also been corrected. This pertains to harmonization required to extend the test coverage (issue #118)

### Additional notes

As it is stated in issue #118 comments, there were a number of issues regarding generating Slovene language words. These have been corrected and tested with yet unpulled patch prepared by @gregopet.

### CODE REVIEW

**Comment by kkonieczny** [comment]
Can you write some tests please since the coverage has decreased by 0.3%

**Comment by gregopet** [comment]
The tests are actually already written in https://github.com/savoirfairelinux/num2words/issues/118 (which cannot be merged as the current faulty implementation does not pass those tests) - we have a chicken & egg problem here.

Unless we resort to some serious git-foo, I suggest either somebody merges both branches (maybe on a new branch until it's 'proven' that the tests now pass and from there into master?) or that @bblaz simply copies my tests into his pull request - I have no problems with it, as long as we fix the current implementation :)

**Comment by erozqba** [comment]
Thanks a lot, @bblaz, for taking the time to make this contribution.
Please, copy the tests written on PR #118 to this PR and make sure they pass.

**Comment by bblaz** [comment]
To me it is not clear what the failure is. Can anyone explain?

**Comment by erozqba** [comment]
@bblaz https://travis-ci.org/savoirfairelinux/num2words/jobs/512632502 
```
ERROR: /home/travis/build/savoirfairelinux/num2words/tests/test_cli.py Imports are incorrectly sorted.
--- /home/travis/build/savoirfairelinux/num2words/tests/test_cli.py:before	2019-03-29 16:41:37.984251
+++ /home/travis/build/savoirfairelinux/num2words/tests/test_cli.py:after	2019-03-29 16:41:54.089922
```

**Pull request merged**
