### PR TITLE
Added support for Mongolian language

### PR DESCRIPTION
**Pull request by oyunsuren**
### Changes proposed in this pull request:
* Added support for Mongolian currency (lang_MN)

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

from num2words import num2words
a = 1234.01
num2words(a, lang='mn')

### Additional notes

*If applicable, explain the rationale behind your change.*

### CODE REVIEW

**Review by TselmegGantuya — DISMISSED** [review]
This is approved for Mongolian currency amount to words.

**Comment by TabooMN** [comment]
Good project. We are need Mongolian language and we are support this project.

**Review by TabooMN — DISMISSED** [review]
Thank you for developing for Mongolian people.

**Comment by oyunsuren** [comment]
Thanks guys. 
Now I need to fix The Travis CI build failures. Is there anyone could advise me how to fix these?

**Comment by erozqba** [comment]
@oyunsuren you can click on the link [Details](https://travis-ci.org/savoirfairelinux/num2words/builds/496905940?utm_source=github_status&utm_medium=notification) and see the logs to find out what is happening.

**Comment by oyunsuren** [comment]
@erozqba Thank you. Will do it.

**Pull request closed without merging**
