### PR TITLE
Polishordinals

### PR DESCRIPTION
**Pull request by PaulinaKomorek**
### Changes proposed in this pull request:

* added support for polish ordinal numbers

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

*unit tests cover all of the possible cases*

### Additional notes

*-*

### CODE REVIEW

**Comment by PaulinaKomorek** [comment]
@mromdhane
Could I kindly ask you for a review?

**Comment by mromdhane** [comment]
@PaulinaKomorek  Can you rebase/Squash commits into one please. I am reviewing it .

**Comment by PaulinaKomorek** [comment]
@mromdhane Sorry, I am afraid I am not experienced enough in git, so I was unable to rebase it successfully, instead. I created a new commit with the proper message and all changes and force-pushed it into this branch. I hope that it is enough.

**Comment by PaulinaKomorek** [comment]
Hello, @mromdhane  any update on this topic?

**Comment by mromdhane** [comment]
Hi @PaulinaKomorek Yes I check it, Can you merge master with your branch, please?

**Comment by PaulinaKomorek** [comment]
@mromdhane Done. Thank you!

**Review by mromdhane — APPROVED** [review]

**Pull request merged**
