### PR TITLE
Release 0.5.8

### PR DESCRIPTION
**Pull request by erozqba**
Hey, it's a good time to make a new release, what do you think guys?

### CODE REVIEW

**Comment by ventilooo** [comment]
LGTM 👌

**Comment by erozqba** [comment]
@maximest-pierre I don't know what it's happening between Travis and Coveralls. We never get any report from Coveralls, but all is OK on Travis. 

Do you have the admin privileges to override the required statuses?
Please merge this and let me know so I can make the release on PyPi.
Thanks a lot.

**Comment by maximest-pierre** [comment]
@erozqba It's merge. I have some free time right now. I am going to look at why coveralls is acting weird.

**Comment by maximest-pierre** [comment]
@erozqba The coveralls token was out of sync on Travis, it should be all good from now on.

**Pull request merged**
