### PR TITLE
Long form for currency name is optional. Currency name rendering in e…

### PR DESCRIPTION
**Pull request by shulcsm**

### CODE REVIEW

**Comment by shulcsm** [comment]
Perhaps `prefix` should be named something else.
I'd like to just break the AP so i don't have to do ugly `if 'currency' in kwargs:`. `to_splitnum` is still there for everyone who wants the old API. What do you think?

**Comment by erozqba** [comment]
Hello @shulcsm 
I think is a good path to follow but there are some code duplications that we should try to avoid.
Maybe we could : 
1. Implement the function `to_currency` in the files `lang_LV.py`, `lang_PL.py`, `lang_RU.py`, `lang_UK.py` as the default behavior in the base class `Num2Word_Base` because the actual `to_currency` in this class is not really useful.
2. Make the class in these files (`lang_LV.py`, `lang_PL.py`, `lang_RU.py`, `lang_UK.py`) inherits from `Num2Word_Base` and made all the functions in the file methods of the class, so we could void code duplications thought inheritance. 

What do you think?

The code duplication is already in place, and I'm OK with merging this and begin the refactoring on another pull request.

**Comment by shulcsm** [comment]
OK, i will try generalizing it  and moving it down to base.

**Comment by erozqba** [comment]
@shulcsm thanks a lot! 
I will merge this work, and you could make a new PR with the new changes.

**Pull request merged**
