### PR TITLE
feat(num2words): translating numbers to letters in spanish mexico

### PR DESCRIPTION
**Pull request by atonaltzin**
translating numbers to letters in spanish mexico

### CODE REVIEW

**Comment by toofun666** [comment]
Do not forget to include your language in the readme.rst file!

**Comment by piranna** [comment]
@atonaltzin, could you be able to explain the differnce between `es` and `es_MX`? So far I see them equal... (I'm from Spain).

**Comment by williamjmorenor** [comment]
I am from nicaragua and I think a single "es" lang should cover fine all countries, some countries uses "centavos" and others ones uses "centimos" , may a option to specifi the subtle differences between countries would be more usefull

**Comment by piranna** [comment]
> I am from nicaragua and I think a single "es" lang should cover fine all countries, some countries uses "centavos" and others ones uses "centimos" , may a option to specifi the subtle differences between countries would be more usefull

That would not work, is better to do a generic `es` and later inherit from it for the different locales as I did for French locales.

**Comment by erozqba** [comment]
I agree with @piranna, the main problem right now is that this other es_* only differ in the to_currency() converter, and there is no test for this. I think that most of this doesn't work properly.

**Comment by williamjmorenor** [comment]
Maybe sing up the project in a service like https://coveralls.io/ can give usefull information about what parts of the code are out of test and this way we can add more tests cases to the project.

**Comment by piranna** [comment]
> Maybe sing up the project in a service like https://coveralls.io/ can give usefull information about what parts of the code are out of test and this way we can add more tests cases to the project.

I like the idea.

**Comment by erozqba** [comment]
@piranna @williamjmorenor I added adding coveralls, flake8 and isort. I'm from Cuba, so I will be able to work in a general `es` class and make others classes inherit from it like in French.

**Comment by piranna** [comment]
> I will be able to work in a general es class and make others classes inherit from it like in French

Good idea! :-)

**Comment by erozqba** [comment]
@shulcsm is refactoring the code of to_currency() to make it possible to use a different currency in different languages, so this PR is no longer valid. 
For exemple, we could want to do :


```
>>> num2words('38.4', lang='es', to='currency', seperator='y', cents=True, currency='CAD', adjective=False)
>>> treinta y ocho dolares y cuarenta centavos

```

**Comment by agb80** [comment]
@erozqba could you please indicate me where can I check the refactoring you talk about?

**Comment by erozqba** [comment]
@agb80 it's already merged, but we need to implement it in others languages, you could check the PR #135

**Pull request closed without merging**
